# Generated by Django 4.1.3 on 2022-11-26 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dudas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=250, null=True)),
                ("descripcion", models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=250, null=True)),
                ("apellidos", models.CharField(max_length=250, null=True)),
                ("fecha", models.CharField(max_length=250, null=True)),
                ("asunto", models.CharField(max_length=250, null=True)),
                ("correo", models.CharField(max_length=250, null=True)),
                ("comentarios", models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="tienda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=250, null=True)),
                ("apellido", models.CharField(max_length=250, null=True)),
                ("correo", models.CharField(max_length=250, null=True)),
                ("numero", models.CharField(max_length=250, null=True)),
                ("pago", models.BooleanField(default=False, null=True)),
                ("total", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tienda",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_propiedad", models.CharField(max_length=250, null=True)),
                ("tipo_propiedad", models.CharField(max_length=250, null=True)),
                ("ubicacion", models.CharField(max_length=250, null=True)),
                ("metros_cuadrados", models.CharField(max_length=250, null=True)),
                ("renta_o_venta", models.CharField(max_length=250, null=True)),
                ("precio", models.CharField(max_length=300, null=True)),
                ("n_habitaciones", models.CharField(max_length=250, null=True)),
                ("estado_habitaciones", models.CharField(max_length=250, null=True)),
                ("disponible", models.BooleanField(default=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
