# Generated by Django 4.1.3 on 2022-11-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instalacionapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quejas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=250, null=True)),
                ("descripcion", models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
