# Generated by Django 4.1.3 on 2022-11-27 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instalacionapp", "0002_quejas"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quejas", old_name="descripcion", new_name="descripcion2",
        ),
        migrations.RenameField(
            model_name="quejas", old_name="nombre", new_name="nombre2",
        ),
    ]
