# Generated by Django 4.1.3 on 2022-11-27 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instalacionapp", "0003_rename_descripcion_quejas_descripcion2_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contrata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.IntegerField(max_length=10, null=True)),
                ("descripcion3", models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
