# Generated by Django 4.1.3 on 2022-11-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instalacionapp", "0004_contrata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrata",
            name="numero",
            field=models.FloatField(max_length=10, null=True),
        ),
    ]
