# Generated by Django 3.2.10 on 2022-11-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalacionapp', '0005_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
