# Generated by Django 4.1.3 on 2022-11-28 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instalacionapp", "0006_contacto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacto",
            name="Nombre",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
