# Generated by Django 4.1.3 on 2022-11-28 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instalacionapp", "0007_alter_contacto_nombre"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contacto", old_name="Nombre", new_name="Nombre4",
        ),
        migrations.RenameField(
            model_name="contacto", old_name="email", new_name="email4",
        ),
        migrations.RenameField(
            model_name="contacto", old_name="mensaje", new_name="mensaje4",
        ),
    ]
