# Generated by Django 4.1.3 on 2022-11-28 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instalacionapp", "0008_rename_nombre_contacto_nombre4_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="Contacto", new_name="Contactosunicos",),
        migrations.DeleteModel(name="Usuario",),
    ]
