# Generated by Django 4.1.3 on 2022-11-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instalacionapp", "0009_rename_contacto_contactosunicos_delete_usuario"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nombre", models.FloatField(max_length=20, null=True)),
                ("email", models.CharField(max_length=30, null=True)),
                ("mensaje", models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=250, null=True)),
                ("apellidos", models.CharField(max_length=250, null=True)),
                ("fecha", models.CharField(max_length=250, null=True)),
                ("asunto", models.CharField(max_length=250, null=True)),
                ("correo", models.CharField(max_length=250, null=True)),
                ("comentarios", models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.DeleteModel(name="Contactosunicos",),
    ]
